### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by Simong2214** [Simong2214/AWS_Scripts#7]
```html
<html>
    <head>
        <title>Stripe Gradient</title>
        <!-- Call script.js -->
        <script defer src="script.js"></script>
        <!-- Call style.css -->
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
       
        
        <canvas id="gradient-canvas">
        </canvas>

        <div style="display: flex; justify-content: center; align-items: center">
            <img src="Group.svg" style="width: 800px; height: 100vh"/>
        </div>
        
    </body>
</html>
```

**Comment by Simong2214** [comment]
```css
html,body {
    margin:0;
    padding:0;
    width:100%;
    height:100%;
    overflow:hidden;
  }
  #gradient-canvas {
    width:100%;
    height:100%;
    --gradient-color-1: #FCE010; 
    --gradient-color-2: #F03FF5; 
    --gradient-color-3: #7428BA;  
    --gradient-color-4: #F1CA05;
    z-index:0;
  }
  
  h1{
    font-family: sohne-var, "Helvetica Neue", Arial, sans-serif;
    font-weight: 800;
    font-size:4rem;
    color: #343434;
    position:absolute;
    padding: 2rem;
    top:0px;
    z-index:100;
    text-align:center;
    width:100%;
    mix-blend-mode: difference;
  }
```
